name: Makefile CI

on:
  push:
    branches: [ "utf8_v1.3" ]
  pull_request:
    branches: [ "utf8_v1.3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: autogen
      run: sh autogen.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssh-dev libsystemd-dev
          
    - name: configure
      run: ./configure

    - name: Run make
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
